---
- name: Common tasks FTW
  hosts: all
  sudo: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Base big service
  hosts: base
  sudo: yes
  roles:
    - { role: big-service, tags: big-service }
    - { role: panda-service, tags: panda-service } 
